### PR TITLE
Fix test_misc_xpu: Update for upstream dynamo refactoring

### LINKED ISSUE #4217: [split from #4211] test_misc_xpu: dynamo var_getattr renamed to getattro_impl (test porting)
### 🐛 Describe the bug

**Affected tests (2):**
- `MiscTests.test_inspect_variable_redirect`
- `MiscTests.test_getattrvariable_as_python_constant`

**Root cause:** Two dynamo refactoring PRs landed between the good and bad commits, and the XPU test port `test/xpu/dynamo/test_misc_xpu.py` was not updated:

1. **PR #186013** (commit `18e1ec10f24`) — global rename `var_getattr → getattro_impl` across all `VariableTracker` subclasses. `InspectVariable.var_getattr` no longer exists, causing `AttributeError: type object 'InspectVariable' has no attribute 'var_getattr'` at test line ~12735.

2. **PR #187196** (commit `6d665f54aa9`) — `GetAttrVariable.as_python_constant` is no longer invoked during attribute access; `CallMethodVariable.as_python_constant` is called instead. The XPU test still patches `GetAttrVariable`, so `po.call_count` stays 0, causing `AssertionError: 0 not greater than 0`.

**Fix in `test/xpu/dynamo/test_misc_xpu.py`:**

For `test_inspect_variable_redirect` (~line 12727):
```python
# Before:
original_var_getattr = InspectVariable.var_getattr
def tracking_var_getattr(self, tx, name): ...
with patch.object(InspectVariable, "var_getattr", tracking_var_getattr):
# After:
original_getattro_impl = InspectVariable.getattro_impl
def tracking_getattro_impl(self, tx, name): ...
with patch.object(InspectVariable, "getattro_impl", tracking_getattro_impl):
```

For `test_getattrvariable_as_python_constant` (~line 13140):
```python
# Before:
from torch._dynamo.variables.misc import GetAttrVariable
with patch.object(GetAttrVariable, "as_python_constant", autospec=True) as po:
# After:
from torch._dynamo.variables.misc import CallMethodVariable as CMV
with patch.object(CMV, "as_python_constant", autospec=True) as po:
```

**Reproducer:**
```bash
cd third_party/torch-xpu-ops/test/xpu/dynamo && \
  python -m pytest -sxv test_misc_xpu.py -k "test_inspect_variable_redirect or test_getattrvariable_as_python_constant"
```

### Versions

- PyTorch version: `2.14.0a0+gita0f2bdc`
- Good commit: `de829759c7e622b806788914ed98a6160b2c5f1c`
- Bad commit: `a0f2bdc50c8590762d0c9ff73bd1801898707001`
- Upstream fix commit: `e356f51370f` (PR #188591, 2026-07-02)
- Hardware: Intel Data Center GPU Max 1100

### PR DESCRIPTION
**Pull request by tszulist-hbn**
Fixes https://github.com/intel/torch-xpu-ops/issues/4217
Fixes two test failures in `test/xpu/dynamo/test_misc_xpu.py` caused by upstream PyTorch dynamo refactoring that renamed methods but weren't reflected in the XPU test file.

## Root Cause

Two upstream refactoring PRs landed between the good and bad commits:

1. **PR #186013**: Renamed `var_getattr` → `getattro_impl` across all `VariableTracker` subclasses
2. **PR #187196**: Moved `as_python_constant` call path from `GetAttrVariable` to `CallMethodVariable`

The XPU test file wasn't updated to match, causing `AttributeError` and assertion failures.

## Changes

- **`test_inspect_variable_redirect`**: Updated all references from `var_getattr` to `getattro_impl`
- **`test_getattrvariable_as_python_constant`**: Changed import and patch target from `GetAttrVariable` to `CallMethodVariable as CMV`

These changes mirror upstream `test/dynamo/test_misc.py` (PR #188591). Pure test porting fix — no XPU operator code involved.

## Test Plan

```bash
pytest test/xpu/dynamo/test_misc_xpu.py::MiscTests::test_inspect_variable_redirect -xvs
pytest test/xpu/dynamo/test_misc_xpu.py::MiscTests::test_getattrvariable_as_python_constant -xvs
```
Both tests now pass.

### CODE REVIEW

**Review by BBBela — APPROVED** [review]
Looks like straightforward 1 to 1 alignment with upstream.
Thanks!

**Review by pbielak — APPROVED** [review]

**Review by PatrykWilczewski — APPROVED** [review]
