### PR TITLE
build: fix build with dpclang after streamlining device compilation

### LINKED ISSUE #5052: dpclang: build with dpclang fails with error: unknown argument: '-no-intel-lib=libirc'
https://github.com/intel/torch-xpu-ops/actions/runs/32423571564/job/96602389334?pr=5010

```
2026-08-20T22:49:44.7874900Z clang++: error: unknown argument: '-no-intel-lib=libirc'
```

The option was introduced by https://github.com/intel/torch-xpu-ops/commit/2f80608ad from @chunhuanMeng. The commit is a big change modifying how kernels getting built. We need to verify and adjust build procedure for dpclang.

CC: @mengfei25, @chuanqi129

### PR DESCRIPTION
**Pull request by dvrogozh**
Fixes: https://github.com/intel/torch-xpu-ops/issues/5052
Fixes: 2f80608a (Remove -fsycl-host-compiler, use pure icpx compilation (#2994))

CC: @chunhuanMeng. @mengfei25, @chuanqi129

### CODE REVIEW

**Review by chunhuanMeng — APPROVED** [review]

**Comment by dvrogozh** [comment]
There are 2 failures in the CI:
```
2026-08-21T04:43:43.0562975Z   File "/__w/torch-xpu-ops/torch-xpu-ops/pytorch/third_party/torch-xpu-ops/test/xpu/test_unary_ufuncs_xpu.py", line 67, in <module>
2026-08-21T04:43:43.0563634Z     TestUnaryUfuncs.test_tan_complex_cuda_matches_numpy
2026-08-21T04:43:43.0564282Z AttributeError: type object 'TestUnaryUfuncs' has no attribute 'test_tan_complex_cuda_matches_numpy'. Did you mean: 'test_tan_complex_matches_numpy'?
```
and
```
2026-08-21T04:32:27.9429404Z worker 'gw10' crashed while running 'third_party/torch-xpu-ops/test/xpu/test_sparse_xpu.py::TestSparseAnyXPU::test_binary_operation_mul_SparseBSR_xpu_float64'
```

Per the nature of the change, I believe above is a noise unrelated to the change. @chuanqi129 , how do you think?

**Comment by dvrogozh** [comment]
I've updated branch. Let's see if failures will be the same.

**Comment by dvrogozh** [comment]
Ok, on the rebased PR with the identical changes failures are all different except for `test_unary_ufuncs_xpu` which is clearly unrelated to this PR. Overall, the CI failures are not related to this PR and PR can be merged.
``` 
op_ut,,third_party.torch-xpu-ops.test.xpu.nn.test_init_xpu
op_ut,,third_party.torch-xpu-ops.test.xpu.nn.test_pooling_xpu
op_ut,third_party.torch-xpu-ops.test.xpu.test_modules_xpu.TestModuleXPU,test_non_contiguous_tensors_nn_Conv3d_xpu_float32
op_ut,,third_party.torch-xpu-ops.test.xpu.test_unary_ufuncs_xpu
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_bfloat16
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_bool
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_float16
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_float32
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_float64
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_float8_e4m3fn
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_float8_e5m2
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_int16
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_int32
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_int64
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_int8
op_ut,third_party.torch-xpu-ops.test.xpu.test_foreach_xpu.TestForeachXPU,test_foreach_copy_with_different_device_inputs__foreach_copy_xpu_uint8
op_ut,third_party.torch-xpu-ops.test.xpu.test_ops_xpu.TestCommonXPU,test_numpy_ref_linalg_tensorinv_xpu_float64
```

**Comment by dvrogozh** [comment]
@torchxpubot merge -f

**Comment by dvrogozh** [comment]
@chuanqi129 , @mengfei25 , need 1 more review to merge. Can you, please, help?

**Review by mengfei25 — APPROVED** [review]

**Comment by dvrogozh** [comment]
@torchxpubot merge -f
