### ISSUE TITLE
[XPU alignment] pytorch/pytorch #189412: PR adds Dynamo support for the curried checkpoint calling convention introduced by PR #189411

### ISSUE THREAD

**Issue by laifenxiawucha** [intel/torch-xpu-ops#4561]
## Upstream Reference
- **Source**: https://github.com/pytorch/pytorch/pull/189412
- **Upstream state** (as of 2026-07-28T00:00:00Z): PR #189412 open (gh api: state=open). Companion PR #189411 closed/landed via ghstack.

## Summary

PR adds Dynamo support for the curried checkpoint calling convention introduced by PR #189411. Before this fix, torch.compile + checkpoint(use_reentrant=False)(fn) raises TypeError. Bug in shared torch/_dynamo (VariableBuilder). Output log confirms TypeError on XPU nightly under torch.compile. PR is open. No XPU tracker found. Companion to pr_189411; both describe the same user-facing API gap.

## XPU Evidence

Output log lines: 'TypeError: checkpoint() missing 1 required positional argument: function'. RESULT: confirmed. Script calls torch.compile(fn)(x) where fn uses curried checkpoint, traceable to PR diff in artifacts/details/pr_189412.json.

## Reproducer

- Script: `scripts/repro_pr_189412.py`
- Output log: `artifacts/output_pr_189412.log`

## Action Required

Track landing of the upstream fix in XPU nightly. Once the fix lands in `pytorch/pytorch` main, verify on the XPU nightly and close this issue.

---
*Auto-filed by XPU alignment run 2026-07-01-to-2026-07-23*

**Comment by laifenxiawucha** [comment]
## Agent Triage Result

**Stage**: WAITING_UPSTREAM  
**Target repo**: pytorch/pytorch  
**Verdict**: NEEDS_HUMAN  
**Upstream reference**: https://github.com/pytorch/pytorch/pull/189412

### Root Cause Analysis
PR adds Dynamo support for the curried checkpoint calling convention introduced by PR #189411. Before this fix, torch.compile + checkpoint(use_reentrant=False)(fn) raises TypeError. Bug in shared torch/_dynamo (VariableBuilder). Output log confirms TypeError on XPU nightly under torch.compile. PR is open. No XPU tracker found. Companion to pr_189411; both describe the same user-facing API gap.

### XPU Evidence
Output log lines: 'TypeError: checkpoint() missing 1 required positional argument: function'. RESULT: confirmed. Script calls torch.compile(fn)(x) where fn uses curried checkpoint, traceable to PR diff in artifacts/details/pr_189412.json.

### Action
The root cause and fix are in `pytorch/pytorch` shared code (not XPU-specific). This XPU tracker monitors whether the upstream fix lands in the XPU nightly build. Once the upstream PR merges and is included in a XPU nightly >= 2.14.0.dev20260713, verify with the reproducer at `scripts/repro_pr_189412.py` and close this issue.

**Upstream state** (as of 2026-07-28T00:00:00Z): PR #189412 open (gh api: state=open). Companion PR #189411 closed/landed via ghstack.

---
*Auto-triaged by XPU alignment run 2026-07-01-to-2026-07-23*
